### ISSUE TITLE
截断文字，后面显示...

### ISSUE THREAD

**Issue by dunizb** [clteam/h5skills#5]
如下代码，Sass
```css
// 截断文字，后面显示...
@mixin textEllipsis($showLine:2) {
  display: -webkit-box !important;
  overflow: hidden;
  text-overflow: ellipsis;
  word-break: break-all;
  /* autoprefixer: off */
  -webkit-box-orient: vertical; // 参考 https://github.com/postcss/autoprefixer/issues/776
  /* autoprefixer: on */
  -webkit-line-clamp:$showLine;
}
```
**问题**
`-webkit-box-orient: vertical`属性不被Webpack处理，被忽略

**解决方案**
/* autoprefixer: off */
  -webkit-box-orient: vertical; // 参考 [https://github.com/postcss/autoprefixer/issues/776](https://github.com/postcss/autoprefixer/issues/776)
  /* autoprefixer: on */
